version: '4.1'

services:
  bd-alliance:
    image: mysql:lts
    command:
      [
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      ]
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: erp
      MYSQL_ROOT_PASSWORD: passw0rd
      MYSQL_ROOT_HOST: "%"
    container_name: "bd-alliance"
    volumes:
      - alliance_erp_data:/var/lib/mysql

volumes:
  alliance_erp_data:


